name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas
        run: npm test

  build-push:
    needs: build-test

    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Login en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir imagen
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/inventario-app:${{ github.sha }} \
                      -t ghcr.io/${{ github.repository_owner }}/inventario-app:latest .

      - name: Publicar imagen
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/inventario-app:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/inventario-app:latest